### ISSUE TITLE
Running error: UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte

### ISSUE THREAD

**Issue by wangyujie000** [EMBL-PKU/BASALT#21]
I used contigs.fa sr.fq nanopore.fq to run. Here is another error:
Traceback (most recent call last):
  File "/home/xxx/mambaforge-pypy3/envs/BASALT/bin/BASALT", line 141, in <module>
    BASALT_main_c(assembly_list, datasets, num_threads, lr_list, hifi_list, hic_list, eb_list, ram, continue_mode, functional_module, autobining_parameters, refinement_paramter, max_ctn, min_cpn, pwd, QC_software)
  File "/home/xxx/mambaforge-pypy3/envs/BASALT/bin/BASALT_main_c.py", line 519, in BASALT_main_c
    polishing_main(best_binset_after_contig_retrieve, datasets, assembly_list, lr_list, 1, 'bw2', 3, ram, num_threads)
  File "/home/xxx/mambaforge-pypy3/envs/BASALT/bin/S7lr_finding_sr_contigs_basing_lr_and_polishing_checkm.py", line 989, in polishing_main
    bin_lr.update(parse_lr_sam('lr'+str(n)+'.sam', lrs, n))
  File "/home/xxx/mambaforge-pypy3/envs/BASALT/bin/S7lr_finding_sr_contigs_basing_lr_and_polishing_checkm.py", line 289, in parse_lr_sam
    for line in open(long_read,'r'):
  File "/home/xxx/mambaforge-pypy3/envs/BASALT/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Is there a solution?

**Comment by EMBL-PKU** [comment]
Is there any Chinese character present in the command? Could you please provide more detail information for this error? Or you can add my wechat account: yukechris and send me those more detailed error information.

**Comment by osvatic** [comment]
Is there a fix for this issue? 

I am getting the same issue while running the following command:

```
BASALT -a 1_HYBRID_scaffolds_1000bp.fa,2_HYBRID_scaffolds_1000bp.fa,3_HYBRID_scaffolds_1000bp.fa,4_HYBRID_scaffolds_1000bp.fa,5_HYBRID_scaffolds_1000bp.fa,6_HYBRID_scaffolds_1000bp.fa -s 1.1.fastq.gz,1.2.fastq.gz/2.1.fastq.gz,2.2.fastq.gz/3.1.fastq.gz,3.2.fastq.gz/4.1.fastq.gz,4.2.fastq.gz/5.1.fastq.gz,5.2.fastq.gz/6.1.fastq.gz,6.2.fastq.gz  -l 1D-ONT.fastq.gz,2D-ONT.fastq.gz,3D-ONT.fastq.gz,4D-ONT.fastq.gz,5D-ONT.fastq.gz,6D-ONT.fastq.gz -t 32 -m 500
```
