### ISSUE TITLE
ModuleNotFoundError: No module named 'symbol'

### ISSUE THREAD

**Issue by haihao999** [EMBL-PKU/BASALT#24]
余老师好，
请问这个问题怎么解决，谢谢！
Traceback (most recent call last):
  File "/home/shang/miniconda3/envs/BASALT/bin/BASALT", line 136, in <module>
    from BASALT_main_d import * 
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shang/miniconda3/envs/BASALT/bin/BASALT_main_d.py", line 11, in <module>
    from S4_Multiple_Assembly_Comparitor_multiple_processes_bwt_10242023 import *
  File "/home/shang/miniconda3/envs/BASALT/bin/S4_Multiple_Assembly_Comparitor_multiple_processes_bwt_10242023.py", line 2, in <module>
    from symbol import except_clause
ModuleNotFoundError: No module named 'symbol'

**Comment by terfait** [comment]
Hi, did you figure out how to fix this?
