### ISSUE TITLE
UnboundLocalError: local variable 'bam_sorted2' referenced before assignment

### ISSUE THREAD

**Issue by Aveglia** [EMBL-PKU/BASALT#25]
Hello, really looking forward to using the program, but I keep hitting this error when I installed using the installation python script as well as building the conda environemnt manually.

Here is the command:
BASALT -a PRPI1_scaffold_1k.fasta -s ../../cleaned/PRPI1.clean.R2.fastq,../../cleaned/PRPI1.clean.R2.fastq -e m -t 2 -m 32

Here is the error:
Traceback (most recent call last):
  File "/home/.ana/envs/BASALT/bin/BASALT", line 141, in <module>
    BASALT_main_c(assembly_list, datasets, num_threads, lr_list, hifi_list, hic_list, eb_list, ram, continue_mode, functional_module, autobining_parameters, refinement_paramter, max_ctn, min_cpn, pwd, QC_software)
  File "/home/.ana/envs/BASALT/bin/BASALT_main_c.py", line 258, in BASALT_main_c
    A=autobinner_main(assembly_list, datasets, lr_list, hifi_list, insert_size, num_threads, ram, autobining_parameters, QC_software, pwd)
  File "/home/.ana/envs/BASALT/bin/S1_Autobinners_2qc_11152023.py", line 1109, in autobinner_main
    bam_sorted=bam_sorted2
UnboundLocalError: local variable 'bam_sorted2' referenced before assignment

Thanks for the awesome program! Super pumped to get it working on my system

**Comment by EMBL-PKU** [comment]
Hi,
BASALT does not support inputting the data with a path, e.g. ../../clean... if you remove the path, the error may disappear.
BTW, we will try to update BASALT to support inputting data with a path. Thank you

**Comment by Xinpeng021001** [comment]
Hi, I used this command:
BASALT -a contigs.fasta -s R1.fq.gz/R2.fq.gz -t 40 -m 900

which also gives me the same issue.
:
Traceback (most recent call last):
  File "/home/xinpeng/miniconda3/envs/BASALT/bin/BASALT", line 141, in <module>
    BASALT_main_c(assembly_list, datasets, num_threads, lr_list, hifi_list, hic_list, eb_list, ram, continue_mode, functional_module, autobining_parameters, refinement_paramter, max_ctn, min_cpn, pwd, QC_software)
  File "/home/xinpeng/miniconda3/envs/BASALT/bin/BASALT_main_c.py", line 258, in BASALT_main_c
    A=autobinner_main(assembly_list, datasets, lr_list, hifi_list, insert_size, num_threads, ram, autobining_parameters, QC_software, pwd)
  File "/home/xinpeng/miniconda3/envs/BASALT/bin/S1_Autobinners_2qc_11152023.py", line 1109, in autobinner_main
    bam_sorted=bam_sorted2
UnboundLocalError: local variable 'bam_sorted2' referenced before assignment
