### ISSUE TITLE
UnboundLocalError: local variable 'target_bin_folder' referenced before assignment

### ISSUE THREAD

**Issue by Songq-20** [EMBL-PKU/BASALT#30]
Dear BASALT Team:
I entered Hi-Fi sequencing data and reported an error：
```
Traceback (most recent call last):
  File "/data01nfs/user/songq/anaconda3/envs/BASALT/bin/BASALT", line 137, in <module>
    BASALT_main_d(assembly_list, datasets, num_threads, lr_list, hifi_list, hic_list, eb_list, ram, continue_mode, functional_module, autobining_parameters, refinement_paramter, max_ctn, min_cpn, pwd, QC_software)
  File "/data01nfs/user/songq/anaconda3/envs/BASALT/bin/BASALT_main_d.py", line 672, in BASALT_main_d
    f_cp_m.write('\n'+'8th contig OLC did not perform!'+'\t'+target_bin_folder)
UnboundLocalError: local variable 'target_bin_folder' referenced before assignment
```
My command is :
```
conda activate BASALT
export CHECKM2DB="/datanode03/huangxy/database/checkm_data/CheckM2_database/uniref100.KO.1.dmnd"

BASALT -a assembly.fasta,MV_CE1k.fasta -hf P05DY231005302-1_r84069_20231107_092926_1_C01.hifi_reads.fastq -s CK_Virome.R1_val_1.fq.gz,CK_Virome.R2_val_2.fq.gz/Lignin_Virome.R1_val_1.fq.gz,Lignin_Virome.R2_val_2.fq.gz/Xylan_Virome.R1_val_1.fq.gz,Xylan_Virome.R2_val_2.fq.gz/Cellulose_Virome.R1_val_1.fq.gz,Cellulose_Virome.R2_val_2.fq.gz -t 30 -m 300 -qc checkm2
```
How can I solve this problem? Thanks！

**Comment by EMBL-PKU** [comment]
You may try the new version of script. I may already fixed the issue. But I am not quite sure. You could try it. I am also going to check it again.

**Comment by Songq-20** [comment]
Thank you for your reply. 
And how can I update the script?

**Comment by noddevil4949** [comment]
You can simply re-download the script provided (it's already updated) to update it. Thanks!
