### ISSUE TITLE
Error when running with test dataset：ModuleNotFoundError: No module named 'torch'

### ISSUE THREAD

**Issue by 1023011930** [EMBL-PKU/BASALT#33]
nohup bash basalt.sh 
[nohup.txt](https://github.com/EMBL-PKU/BASALT/files/15468950/nohup.txt)
[Basalt_log.txt](https://github.com/EMBL-PKU/BASALT/files/15468955/Basalt_log.txt)
[basalt.txt](https://github.com/EMBL-PKU/BASALT/files/15468956/basalt.txt)

**I used tencent cloud‘s basalt_env.yml**

git clone https://github.com/EMBL-PKU/BASALT.git
cd BASALT
conda env create -n BASALT --file basalt_env.yml
#mamba install pytorch torchvision torchaudio -c pytorch
#如果遇到错误，请从腾讯云（https://share.weiyun.com/xXdRiDkl）下载basalt_env.yml并创建conda环境：
conda env create -n BASALT --file basalt_env.yml
#安装的同时下载训练好的模型
https://share.weiyun.com/r33c2gqa
#给权限
chmod -R 777 /home/XX/mambaforge/envs/BASALT/bin/*
mv BASALT.zip ~/.cache
cd ~/.cache
unzip BASALT.zip
BASALT -h

Bug：
4300 sequences 4300 >= 500 bp
4400 sequences 4400 >= 500 bp
4500 sequences 4500 >= 500 bp
4600 sequences 4600 >= 500 bp
4700 sequences 4700 >= 500 bp
4800 sequences 4800 >= 500 bp
Parsing kmer 1_assembly.fa
Reading basic information
Processing Coverage_matrix_for_binning_1_assembly.fa.txt
['1_assembly.fa.kmer.txt']
mkdir: 无法创建目录"BestBinset_outlier_test": 文件已存在
Traceback (most recent call last):
  File "/home/zhongpei/mambaforge/envs/BASALT/bin/ensemble.py", line 10, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
Predicting potential outliers
Traceback (most recent call last):
  File "/home/zhongpei/mambaforge/envs/BASALT/bin/BASALT", line 141, in <module>
    BASALT_main_c(assembly_list, datasets, num_threads, lr_list, hifi_list, hic_list, eb_list, ram, continue_mode, functional_module, autobining_parameters, refinement_paramter, max_ctn, min_cpn, pwd, QC_software)
  File "/home/zhongpei/mambaforge/envs/BASALT/bin/BASALT_main_c.py", line 441, in BASALT_main_c
    outlier_remover_main('BestBinset', coverage_matrix_list, datasets, assembly_mo_list, pwd, num_threads)
  File "/home/zhongpei/mambaforge/envs/BASALT/bin/S5_Outlier_remover_DL_checkm.py", line 452, in outlier_remover_main
    A=outlier_predictor(depth_TNF_matrix, contigs_depth, bin_contigs, datasets, num_threads, nx)
  File "/home/zhongpei/mambaforge/envs/BASALT/bin/S5_Outlier_remover_DL_checkm.py", line 145, in outlier_predictor
    for line in open('Predicted_potential_outlier.txt','r'):
FileNotFoundError: [Errno 2] No such file or directory: 'Predicted_potential_outlier.txt'

**Comment by 1023011930** [comment]
I would appreciate a reply from you guys!

**Comment by EMBL-PKU** [comment]
Hi, 
I guess it is a problem of environment. You may need to re-install BASALT to solve this issue.
Are you from China? If so, 可以加我的微信，yukechris，我看看问题

**Comment by 1023011930** [comment]
**Here's how I solved it**
mamba install pytorch torchvision torchaudio-c pytorch
pip install torch torchvision
mamba install -c conda-forge tensorboardx
