### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'Predicted_potential_outlier.txt'

### ISSUE THREAD

**Issue by Songq-20** [EMBL-PKU/BASALT#42]
Dear BASALT team:
Thank you for your efforts! In BASALT(v1.1.0), the previous problem has been resolved, but I have encountered a new problem:
My commands:
```
export CHECKM2DB="/datanode03/huangxy/database/checkm_data/CheckM2_database/uniref100.KO.1.dmnd"

conda activate BASALT
a=2022_TGL_TJ3-4_megahit.contigs.fa
s1_1=TGL_TT1-2R1_trimmed.fq.gz
s1_2=TGL_TT1-2R2_trimmed.fq.gz
s2_1=TGL_TT3-4R1_trimmed.fq.gz
s2_2=TGL_TT3-4R2_trimmed.fq.gz
s3_1=TGL_TJ3-4R1_trimmed.fq.gz
s3_2=TGL_TJ3-4R2_trimmed.fq.gz
s4_1=TGL_TJ1-2R1_trimmed.fq.gz
s4_2=TGL_TJ1-2R2_trimmed.fq.gz
BASALT -a $a -s $s1_1,$s1_2/$s2_1,$s2_2/$s3_1,$s3_2/$s4_1,$s4_2 -t 20 -m 200 -q checkm2
conda deactivate
```
`basalt.err` : 
```
Traceback (most recent call last):
  File "/data01nfs/user/songq/anaconda3/envs/BASALT/bin/ensemble.py", line 140, in <module>
    main(opt)
  File "/data01nfs/user/songq/anaconda3/envs/BASALT/bin/ensemble.py", line 30, in main
    dataset = MyDataSet_test(type=args.norm_type, use_256=args.use_256, fea=args.fea, split='test', dec=args.dec)
  File "/data01nfs/user/songq/anaconda3/envs/BASALT/bin/my_dataset.py", line 168, in __init__
    datas.append(norm(np.vstack(temp_datas), type))
UnboundLocalError: local variable 'temp_datas' referenced before assignment
Traceback (most recent call last):
  File "/data01nfs/user/songq/anaconda3/envs/BASALT/bin/BASALT", line 219, in <module>
    BASALT_main_d(assembly_list, datasets, num_threads, lr_list, hifi_list, hic_list, eb_list, ram, continue_mode, functional_module, sensitivity, refinement_paramter, max_ctn, min_cpn, pwd, QC_software, output_folder)
  File "/data01nfs/user/songq/anaconda3/envs/BASALT/bin/BASALT_main_d.py", line 456, in BASALT_main_d
    outlier_remover_main('BestBinset', coverage_matrix_list, datasets, lr_list, hifi_list, assembly_mo_list, pwd, num_threads)
  File "/data01nfs/user/songq/anaconda3/envs/BASALT/bin/S5_Outlier_remover_DL_11012023.py", line 549, in outlier_remover_main
    A=outlier_predictor(depth_TNF_matrix, contigs_depth, bin_contigs, datasets, lr, hifi_list, num_threads, nx)
  File "/data01nfs/user/songq/anaconda3/envs/BASALT/bin/S5_Outlier_remover_DL_11012023.py", line 145, in outlier_predictor
    for line in open('Predicted_potential_outlier.txt','r'):
FileNotFoundError: [Errno 2] No such file or directory: 'Predicted_potential_outlier.txt'
```
`Basalt_checkpoint.txt`   ：
```
1st autobinner done!
2nd bin selection within group done!
3rd bin selection did not perform, because there is only one assembly!
```

Looking forward to your reply!

**Comment by vicru93** [comment]
Hi... Yes, the same thing happened to me

**Comment by sersancar** [comment]
Hi. I've found the same error after 1 month running the program over a huge dataset. Hope some reply.

**Comment by chrysanthemyl** [comment]
I'm getting this error as well. Anybody figure out a fix yet?

**Comment by SamBrutySci** [comment]
> I'm getting this error as well. Anybody figure out a fix yet?
> 
> edit: it's because ensemble.py was changed in 1.1.0 and Predicted_potential_outlier.txt is not produced. if you replace ensemble.py with the previous version the file is produced and you can get past this step.


Hi, I'm using BASALT via a singularity image and I'm having the same problem with a large dataset. Were you able to continue your run or did you have to restart? 

Is there any official fix for this?

**Comment by zhaorui-bi** [comment]
@SamBrutySci The newest version of BASALT has been released. You can check the latest README Documents for detials.

<img width="1782" height="528" alt="Image" src="https://github.com/user-attachments/assets/331eac04-e3c5-4df5-a089-67dd3f0606ea" />
