### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'clustering_gt1000.csv'

### ISSUE THREAD

**Issue by tenguzame** [EMBL-PKU/BASALT#45]
Good morning,
I'm trying to run BASALT on a local HPC. I'm trying to bin 2 assemblies using 2 read sets, using the following command:

`srun BASALT.py -a MHallok.fasta -s CC_TOT_03_trim_norm_1.fastq,CC_TOT_03_trim_norm_2.fastq -t 30 -e m -m 350 --mode new`

Everything runs fine, until CONCOCT is run. At that point, the program halts with the following error:

`FileNotFoundError: [Errno 2] No such file or directory: 'clustering_gt1000.csv'`

How do I fix it?

Best regards

**Comment by HaishuMa** [comment]
Hi, @HaiXin-Z @tenguzame  :
I appeared the same question, so I tried the following command: 
```
(basalt_env) [hsma@mu01 UA]$ concoct -h
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.2.3 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/data2/projects/bioinfo/hsma/envs/basaltv/bin/concoct", line 6, in <module>
    import vbgmm
Traceback (most recent call last):
  File "/data2/projects/bioinfo/hsma/envs/basalt_env/bin/concoct", line 6, in <mod>
    import vbgmm
  File "c-concoct/vbgmm.pyx", line 1, in init vbgmm
ImportError: numpy.core.multiarray failed to import (auto-generated because you dit call 'numpy.import_array()' after cimporting numpy; use '<void>numpy._import_arr to disable if you are certain you don't need it).
```

So, I reinstalled the NumPy by the following command: 
`pip install "numpy<2" --break-system-packages` 
After it, the CONCOCT could run and the error disappeared.
I think you should check if your CONCOCT has run.
