### ISSUE TITLE
empty fasta file:'Remapping.fasta'; local variable 'bam_sorted' referenced before assignment

### ISSUE THREAD

**Issue by FengqingWang0712** [EMBL-PKU/BASALT#46]
Hello,
First, thank you for this cool tool.
However, I got this error. It's the latest version by the way. Can you help me with it?
Input files DNA, FASTA:
  Remapping.fasta
Warning: Empty fasta file: 'Remapping.fasta'
Warning: All fasta inputs were empty
Total time for call to driver() for forward index: 00:00:00
Error: Encountered internal Bowtie 2 exception (#1)
Command: /bioinf/home/fwang/software/miniconda3/envs/BASALT-1.1.0/bin/bowtie2-build-s --wrapper basic-0 Remapping.fasta Remapping.fasta 
Traceback (most recent call last):
  File "/bioinf/home/fwang/software/miniconda3/envs/BASALT-1.1.0/bin/S5_Outlier_remover_DL_checkm.py", line 289, in outlier_predictor
    os.system('jgi_summarize_bam_contig_depths --outputDepth Re-mapped_depth.txt '+str(bam_sorted))
UnboundLocalError: local variable 'bam_sorted' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/bioinf/home/fwang/software/miniconda3/envs/BASALT-1.1.0/bin/BASALT", line 141, in <module>
    BASALT_main_c(assembly_list, datasets, num_threads, lr_list, hifi_list, hic_list, eb_list, ram, continue_mode, functional_module, autobining_parameters, refinement_paramter, max_ctn, min_cpn, pwd, QC_software)
  File "/bioinf/home/fwang/software/miniconda3/envs/BASALT-1.1.0/bin/BASALT_main_c.py", line 441, in BASALT_main_c
    outlier_remover_main('BestBinset', coverage_matrix_list, datasets, assembly_mo_list, pwd, num_threads)
  File "/bioinf/home/fwang/software/miniconda3/envs/BASALT-1.1.0/bin/S5_Outlier_remover_DL_checkm.py", line 452, in outlier_remover_main
    A=outlier_predictor(depth_TNF_matrix, contigs_depth, bin_contigs, datasets, num_threads, nx)
  File "/bioinf/home/fwang/software/miniconda3/envs/BASALT-1.1.0/bin/S5_Outlier_remover_DL_checkm.py", line 296, in outlier_predictor
    os.system('jgi_summarize_bam_contig_depths --outputDepth Re-mapped_depth.txt '+str(bam_sorted))
UnboundLocalError: local variable 'bam_sorted' referenced before assignment

**Comment by noddevil4949** [comment]
Hi,

It looks like that there is no fasta file generated in the previous step. Could you please have a check the content in the "BestBinset" folder? If this folder is empty, it means you have either encountered an error at the previous step, or even earlier.

Cheers,
BASALT team

**Comment by FengqingWang0712** [comment]
Thank you for your reply.
The "BestBinset" folder is not empty. Actually it includes many refined bins and statistic files with bins' quality.

Best

**Comment by noddevil4949** [comment]
Hmm it looks weird. Could you please add my Wechat "noddevil4949" so we can have a look at details?

**Comment by Eirwyn-sheen** [comment]
Hello, I have encountered a similar problem.

**Comment by mnter** [comment]
Hello,
I have met the same problem "UnboundLocalError: local variable 'bam_sorted' referenced before assignment".
Also, the "BestBinset" folder is not empty. 
Has the problem been solved?
Thank you

**Comment by Meghana9854** [comment]
Hello,

Thanks for the really nice tool.

I have the same issue. I have many bins within the "BesBinset" direct and still come across the error below.
I have HiFi only data and was wondering if the reassembly step is possible with only long-read (HiFi) data. Or do you require short reads for the the reassembly module to run? 

err.log as below:

Building a SMALL index
Renaming Remapping.fasta.3.bt2.tmp to Remapping.fasta.3.bt2
Renaming Remapping.fasta.4.bt2.tmp to Remapping.fasta.4.bt2
Renaming Remapping.fasta.1.bt2.tmp to Remapping.fasta.1.bt2
Renaming Remapping.fasta.2.bt2.tmp to Remapping.fasta.2.bt2
Renaming Remapping.fasta.rev.1.bt2.tmp to Remapping.fasta.rev.1.bt2
Renaming Remapping.fasta.rev.2.bt2.tmp to Remapping.fasta.rev.2.bt2
Traceback (most recent call last):
  File "/home/msrinivas/miniconda3/envs/BASALT/bin/S5_Outlier_remover_DL_checkm.py", line 289, in outlier_predictor
    os.system('jgi_summarize_bam_contig_depths --outputDepth Re-mapped_depth.txt '+str(bam_sorted))
UnboundLocalError: local variable 'bam_sorted' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/msrinivas/miniconda3/envs/BASALT/bin/BASALT", line 141, in <module>
    BASALT_main_c(assembly_list, datasets, num_threads, lr_list, hifi_list, hic_list, eb_list, ram, continue_mode, functional_module, autobining_parameters, refinement_paramter, max_ctn, min_cpn, pwd, QC_software)
  File "/home/msrinivas/miniconda3/envs/BASALT/bin/BASALT_main_c.py", line 441, in BASALT_main_c
    outlier_remover_main('BestBinset', coverage_matrix_list, datasets, assembly_mo_list, pwd, num_threads)
  File "/home/msrinivas/miniconda3/envs/BASALT/bin/S5_Outlier_remover_DL_checkm.py", line 452, in outlier_remover_main
    A=outlier_predictor(depth_TNF_matrix, contigs_depth, bin_contigs, datasets, num_threads, nx)
  File "/home/msrinivas/miniconda3/envs/BASALT/bin/S5_Outlier_remover_DL_checkm.py", line 296, in outlier_predictor
    os.system('jgi_summarize_bam_contig_depths --outputDepth Re-mapped_depth.txt '+str(bam_sorted))
UnboundLocalError: local variable 'bam_sorted' referenced before assignment

**Comment by zhaorui-bi** [comment]
Thanks for your use for BASALT. Now, we highly recommended you to use https://github.com/PKU-EMBL/BASALT-Air this version and see the detials.
