### ISSUE TITLE
Abnormal Exit in step 8

### ISSUE THREAD

**Issue by f12345zxcvbnm2** [EMBL-PKU/BASALT#52]
Dear BASALT Team:
Thanks for such an amazing tool.
However I am running the  pipline it stop after rerun it showed that:
```BASALT started from step: 8
Starting reassembly
Processing bins in BestBinset_outlier_refined_filtrated_retrieved_OLC
BestBinset_outlier_refined_filtrated_retrieved_OLC_re-assembly_binset exists
BestBinset_outlier_refined_filtrated_retrieved_OLC_sr_bins_seq exists
BestBinset_outlier_refined_filtrated_retrieved_OLC_mod is exist. Re-create the folder
Checking reassembled bins
Reassembly CheckM error! Re-do!
Reassembly CheckM error! Abandon!
Reassembly CheckM error! Abandon!"
```
and the content of the shell is :
```Traceback (most recent call last):
  File "/home/lab/miniconda3/envs/BASALT/bin/BASALT", line 141, in <module>
    BASALT_main_c(assembly_list, datasets, num_threads, lr_list, hifi_list, hic_list, eb_list, ram, continue_mode, functional_module, autobining_parameters, refinement_paramter, max_ctn, min_cpn, pwd, QC_software)
  File "/home/lab/miniconda3/envs/BASALT/bin/BASALT_main_c.py", line 611, in BASALT_main_c
    re_assembly_main(binset_folder, datasets_list, lr_list, hybri_reassembly, ram, num_threads)
  File "/home/lab/miniconda3/envs/BASALT/bin/S9_Reassembly_checkm.py", line 726, in re_assembly_main
    best_bin_after_c=bin_comparison(paired_bins, bin_checkm)
  File "/home/lab/miniconda3/envs/BASALT/bin/S9_Reassembly_checkm.py", line 402, in bin_comparison
    f.write(str(item)+'\t'+str(bin_checkm[best_bin_checkm_name])+'\n')
KeyError: 'bin242'
```
Any response would be greatly appreciated!

**Comment by noddevil4949** [comment]
Hi,

It seems something wrong occurred at step 8. We have received several similar bugs reported, and we are trying to fix this. Here is an alternative way to address this issue:

Edit Basalt_checkpoint.txt. You may probably see this:
1st autobinner done!
2nd bin selection within group done!
3rd bin selection within multiple groups done!
4th outlier removal done!
5th contig retrieve done!
6th secondary de-repplication done!
7th Skip contig retrieve within group!	BestBinset_outlier_refined_filtrated_retrieved
8th contig OLC done!	BestBinset_outlier_refined_filtrated_retrieved_OLC

Delete the last line and re-run BASALT, it should solve this issue.

Thanks,
BASALT team
