### ISSUE TITLE
UnboundLocalError: local variable 'level_num' referenced before assignment

### ISSUE THREAD

**Issue by haihao999** [EMBL-PKU/BASALT#54]
Hi,
 请问老师这个该如何解决?
Coverage matrix: ['Coverage_matrix_for_binning_1_TARA_141_20_180.fa.txt']
.....................................
Trying to read combat bins from the same assembly
2
0
Total 0 iterations
Iteration starts
Traceback (most recent call last):
  File "/home/syp/miniconda3/envs/BASALT/bin/BASALT", line 141, in <module>
    BASALT_main_c(assembly_list, datasets, num_threads, lr_list, hifi_list, hic_list, eb_list, ram, continue_mode, functional_mod>
  File "/home/syp/miniconda3/envs/BASALT/bin/BASALT_main_c.py", line 509, in BASALT_main_c
    Contig_retrieve_within_group_main(best_binset_after_contig_retrieve, outlier_remover_folder, num_threads, continue_mode, cpn_>
  File "/home/syp/miniconda3/envs/BASALT/bin/S7_Contigs_retrieve_within_group_checkm.py", line 1919, in Contig_retrieve_within_gr>
    Contig_retrieve_within_group(assemblies_list, binset, outlier_remover_folder, PE_connections_list, num_threads, last_step, co>
  File "/home/syp/miniconda3/envs/BASALT/bin/S7_Contigs_retrieve_within_group_checkm.py", line 1655, in Contig_retrieve_within_gr>
    os.system('mv *_filtrated_bin_connecting_contigs_'+str(level_num)+'.txt *_eliminated_bin_connecting_contigs_'+str(level_num)+>
UnboundLocalError: local variable 'level_num' referenced before assignment

**Comment by zhaorui-bi** [comment]
可以尝试一下全新的版本
