### ISSUE TITLE
EXTRA_BINNERs didn't start and ZeroDivisionError: division by zero

### ISSUE THREAD

**Issue by rusanovaA** [EMBL-PKU/BASALT#6]
Hi!
I started BASALT with 
```BASALT -a assebmly.fasta -s R1_paired.fastq.gz,R2_paired.fastq.gz -t 50 -e m,v```
but the program ran only maxbin2, metabat and concoct and than falled with that error.
And also in the paper I saw, that BASALT have another extra binners, but there isn't any information in tutorial about tham.
I will be very appreciate for your help!
```Running checkm with binsets gernerated from maxbin2, metabat and concoct
Traceback (most recent call last):
  File "/opt/miniconda3/envs/BASALT/bin/BASALT", line 111, in <module>
    BASALT_main(assembly_list, datasets, num_threads, lr_list, hic_list, eb_list, ram, continue_mode, functional_module, autobining_parameters, refinement_paramter, max_ctn, min_cpn, pwd)
  File "/opt/miniconda3/envs/BASALT/bin/BASALT_main.py", line 257, in BASALT_main
    A=autobinner_main(assembly_list, datasets, num_threads, ram, autobining_parameters, pwd)
  File "/opt/miniconda3/envs/BASALT/bin/S1_Autobinners_06242023.py", line 738, in autobinner_main
    bins_folders[str(assembly_list[item])]=autobinners('all', mo_assembly, mo_assembly_depth, Coverage_list_file, binning_mode, binning_ds, checkm_done_f, num_threads, ram)
  File "/opt/miniconda3/envs/BASALT/bin/S1_Autobinners_06242023.py", line 609, in autobinners
    num_threads_per_project=int(num_threads/checkm_proj_num)+1
ZeroDivisionError: division by zero

**Comment by EMBL-PKU** [comment]
Hi，
I am sorry for the late response. We just fixed bugs and updated. Please refer to the new version of BASALT
