### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/home/data/JGM/BASALT/TMP_D7_E6/BestBinset_outlier_refined_filtrated_retrieved_retrieved_re-assembly_binset_checkm/storage'

### ISSUE THREAD

**Issue by Wang0293** [EMBL-PKU/BASALT#9]
Hello,

I'm trying BASALT with a subset of my data. It looked to work fine until the step  as follows that failed with the error in the title.
```
===== Mismatch correction scaffolds finished. 


===== Mismatch correction finished. 


===== Breaking scaffolds started. 


== Running: /home/dell/miniconda3/envs/BASALT/bin/python /home/dell/miniconda3/envs/BASALT/share/spades/spades_pipeline/scripts/breaking_scaffolds_script.py --result_scaffolds_filename /home/data/JGM/BASALT/TMP_D7_E6/bin109_spades_reassembly/scaffolds.fasta --misc_dir /home/data/JGM/BASALT/TMP_D7_E6/bin109_spades_reassembly/misc --threshold_for_breaking_scaffolds 3


===== Breaking scaffolds finished. 


===== Terminate started. 


===== Terminate finished. 

 * Corrected reads are in /home/data/JGM/BASALT/TMP_D7_E6/bin109_spades_reassembly/corrected/
 * Assembled contigs are in /home/data/JGM/BASALT/TMP_D7_E6/bin109_spades_reassembly/contigs.fasta
 * Assembled scaffolds are in /home/data/JGM/BASALT/TMP_D7_E6/bin109_spades_reassembly/scaffolds.fasta
 * Paths in the assembly graph corresponding to the contigs are in /home/data/JGM/BASALT/TMP_D7_E6/bin109_spades_reassembly/contigs.paths
 * Paths in the assembly graph corresponding to the scaffolds are in /home/data/JGM/BASALT/TMP_D7_E6/bin109_spades_reassembly/scaffolds.paths
 * Assembly graph is in /home/data/JGM/BASALT/TMP_D7_E6/bin109_spades_reassembly/assembly_graph.fastg
 * Assembly graph in GFA format is in /home/data/JGM/BASALT/TMP_D7_E6/bin109_spades_reassembly/assembly_graph_with_scaffolds.gfa

======= SPAdes pipeline finished WITH WARNINGS!

=== Error correction and assembling warnings:
 * 0:00:06.090    28M / 1305M WARN    General                 (kmer_coverage_model.cpp   : 327)   Valley value was estimated improperly, reset to 2
======= Warnings saved to /home/data/JGM/BASALT/TMP_D7_E6/bin109_spades_reassembly/warnings.log

SPAdes log can be found here: /home/data/JGM/BASALT/TMP_D7_E6/bin109_spades_reassembly/spades.log

Thank you for using SPAdes!
number of threads 80
reads 0
long reads 547394
extra reads 0
read_length 0
kmer 20
kmers 4616516 4661192
merge bubble 16365
contigs: 8661 n50: 2438 max: 19898 mean: 402 total length: 3484670 n80: 742
aligned 0 reads
confirmed bases: 0 correct reads: 0 bases: 0
distance mean -nan sd -nan
invalid insert distance
kmer 40
kmers 4520007 4537048
merge bubble 1275
contigs: 3221 n50: 5720 max: 48820 mean: 1078 total length: 3475246 n80: 2007
aligned 0 reads
confirmed bases: 0 correct reads: 0 bases: 0
distance mean -nan sd -nan
invalid insert distance
kmer 60
kmers 4425671 4434254
merge bubble 757
contigs: 1740 n50: 8582 max: 48868 mean: 1978 total length: 3442771 n80: 3183
aligned 0 reads
confirmed bases: 0 correct reads: 0 bases: 0
distance mean -nan sd -nan
invalid insert distance
kmer 80
kmers 4037405 4040396
merge bubble 470
contigs: 1026 n50: 11912 max: 48887 mean: 3313 total length: 3399395 n80: 4504
aligned 0 reads
confirmed bases: 0 correct reads: 0 bases: 0
distance mean -nan sd -nan
invalid insert distance
kmer 100
kmers 3658723 3659078
merge bubble 184
contigs: 935 n50: 12323 max: 74337 mean: 3639 total length: 3403295 n80: 4621
terminate called after throwing an instance of 'std::logic_error'
  what():  SequenceReader::SequenceReader() istream is invalid
Aborted (core dumped)
[2024-03-01 01:58:56] INFO: CheckM v1.1.3
[2024-03-01 01:58:56] INFO: checkm lineage_wf -t 80 -x fa BestBinset_outlier_refined_filtrated_retrieved_retrieved_re-assembly_binset BestBinset_outlier_refined_filtrated_retrieved_retrieved_re-assembly_binset_checkm
[2024-03-01 01:58:56] INFO: [CheckM - tree] Placing bins in reference genome tree.
[2024-03-01 01:58:56] ERROR: Failed to process sequence file: BestBinset_outlier_refined_filtrated_retrieved_retrieved_re-assembly_binset/bin32_IDBA_re-assembly_contigs.fa

  Controlled exit resulting from an unrecoverable error or warning.
Traceback (most recent call last):
  File "/home/dell/miniconda3/envs/BASALT/bin/BASALT", line 111, in <module>
    BASALT_main(assembly_list, datasets, num_threads, lr_list, hic_list, eb_list, ram, continue_mode, functional_module, autobining_parameters, refinement_paramter, max_ctn, min_cpn, pwd)
  File "/home/dell/miniconda3/envs/BASALT/bin/BASALT_main.py", line 610, in BASALT_main
    re_assembly_main(binset_folder, datasets_list, lr_list, hybri_reassembly, ram, num_threads)
  File "/home/dell/miniconda3/envs/BASALT/bin/S9_Reassembly_10282022.py", line 612, in re_assembly_main
    reassembly_bin_checkm=parse_checkm(binset_folder+'_re-assembly_binset_checkm/storage',pwd)
  File "/home/dell/miniconda3/envs/BASALT/bin/S9_Reassembly_10282022.py", line 251, in parse_checkm
    os.chdir(pwd+'/'+checkm_containing_folder)
FileNotFoundError: [Errno 2] No such file or directory: '/home/data/JGM/BASALT/TMP_D7_E6/BestBinset_outlier_refined_filtrated_retrieved_retrieved_re-assembly_binset_checkm/storage'

```
I am looking forwarding to your answering.

**Comment by Wang0293** [comment]
> It might be because there is no bins under the folder. Could you please check whether there is any bin in the folder and let me know? If so, there was an error happened during the binning process. Thank you very much.

I'm sorry for the late reply. I deleted the files before, so I repeated it yesterday.
As the report, it's surely there isn't _storage_ file in the path `/home/data/JGM/BASALT/TMP_D7_E6/BestBinset_outlier_refined_filtrated_retrieved_retrieved_re-assembly_binset_checkm/`.
And I noticed the error `[2024-03-01 01:58:56] ERROR: Failed to process sequence file: BestBinset_outlier_refined_filtrated_retrieved_retrieved_re-assembly_binset/bin32_IDBA_re-assembly_contigs.fa`, this bin‘s last line is a '>'.
I just deleted this bin and run with the continue mode and everything goes well. So I believed you're right, some error happened during the binning process. But I'm cofused, why only this bin file have some error?
There are the bin file and the checkpoint file.
[bin34_IDBA_re-assembly_contigs.txt](https://github.com/EMBL-PKU/BASALT/files/14879124/bin34_IDBA_re-assembly_contigs.txt)
[Basalt_checkpoint.txt](https://github.com/EMBL-PKU/BASALT/files/14879133/Basalt_checkpoint.txt)

**Comment by Wang0293** [comment]
Hi, @EMBL-PKU 
I have used BASALT for my other data, and repeated the bug in some other samples.
However, some samples happened this error and some others not. So I think it's just because the memory of my server isn't enough. All the error happened on the IDBA files, so I think the IDBA may using more memory than the Spades and Megahit, right?
